---
version: "2.1"
services:
  unifi-controller:
    network_mode: host
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-server
    environment:
      - PUID=900
      - PGID=900
      - MEM_LIMIT=1024M #opcional
    volumes:
      - ~/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
    restart: unless-stopped